name: "Main"
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # don't cancel all jobs if some of them failed
      matrix:
        os: [windows-latest, ubuntu-16.04, ubuntu-18.04]
        node: [10, 12, 14]
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install docker-compose
        if: startsWith(matrix.os, 'macos')
        run: brew install docker-compose

      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - name: Test ncc build (for Github Actions)
        run: yarn ncc

  release:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push' && github.ref != 'refs/heads/master' && contains(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
